DROP_TABLES = {
    "炼气前期": [
        {"item": "low_spirit_stone", "weight": 30, "quantity": [6, 14]},
        {"item": "mana_pill", "weight": 18, "quantity": [1, 2]},
        {"item": "healing_pill", "weight": 16, "quantity": [1, 2]},
        {"item": "qi_powder", "weight": 12, "quantity": [1, 2]},
        {"item": "low_material", "weight": 14, "quantity": [1, 3]},
        {"item": "low_method", "weight": 14, "quantity": [1, 1]},
        {"item": "low_artifact", "weight": 12, "quantity": [1, 1]},
        {"item": "foundation_pill", "weight": 5, "quantity": [1, 1]},
        {"item": "spirit_grass", "weight": 20, "quantity": [1, 3]},
        {"item": "clear_dew", "weight": 12, "quantity": [1, 2]},
        {"item": "spirit_paper", "weight": 15, "quantity": [1, 3]},
        {"item": "spirit_ink", "weight": 10, "quantity": [1, 2]},
        {"item": "formation_flag", "weight": 8, "quantity": [1, 2]},
        {"item": "spirit_stone_chip", "weight": 12, "quantity": [2, 5]},
        {"item": "black_iron_shard", "weight": 12, "quantity": [1, 3]},
    ],
    "炼气": [
        {"item": "low_spirit_stone", "weight": 42, "quantity": [4, 12]},
        {"item": "mana_pill", "weight": 12, "quantity": [1, 2]},
        {"item": "healing_pill", "weight": 16, "quantity": [1, 2]},
        {"item": "low_material", "weight": 18, "quantity": [1, 3]},
        {"item": "low_method", "weight": 8, "quantity": [1, 1]},
        {"item": "low_artifact", "weight": 8, "quantity": [1, 1]},
        {"item": "foundation_pill", "weight": 4, "quantity": [1, 1]},
        {"item": "spirit_grass", "weight": 18, "quantity": [1, 3]},
        {"item": "clear_dew", "weight": 10, "quantity": [1, 2]},
        {"item": "spirit_paper", "weight": 14, "quantity": [1, 3]},
        {"item": "spirit_ink", "weight": 8, "quantity": [1, 2]},
        {"item": "formation_flag", "weight": 6, "quantity": [1, 2]},
        {"item": "spirit_stone_chip", "weight": 10, "quantity": [2, 5]},
        {"item": "black_iron_shard", "weight": 10, "quantity": [1, 3]},
    ],
    "筑基": [
        {"item": "mid_spirit_stone", "weight": 45, "quantity": [4, 12]},
        {"item": "healing_pill", "weight": 18, "quantity": [1, 3]},
        {"item": "mid_material", "weight": 22, "quantity": [1, 3]},
        {"item": "mid_method", "weight": 6, "quantity": [1, 1]},
        {"item": "mid_artifact", "weight": 6, "quantity": [1, 1]},
        {"item": "core_pill", "weight": 3, "quantity": [1, 1]},
    ],
    "结丹": [
        {"item": "mid_spirit_stone", "weight": 42, "quantity": [8, 18]},
        {"item": "mid_material", "weight": 24, "quantity": [2, 4]},
        {"item": "mid_method", "weight": 8, "quantity": [1, 1]},
        {"item": "mid_artifact", "weight": 8, "quantity": [1, 1]},
        {"item": "nascent_pill", "weight": 2, "quantity": [1, 1]},
    ],
    "元婴": [
        {"item": "high_spirit_stone", "weight": 45, "quantity": [8, 20]},
        {"item": "high_material", "weight": 25, "quantity": [1, 3]},
        {"item": "high_method", "weight": 7, "quantity": [1, 1]},
        {"item": "high_artifact", "weight": 7, "quantity": [1, 1]},
    ],
    "化神": [
        {"item": "high_spirit_stone", "weight": 45, "quantity": [12, 28]},
        {"item": "high_material", "weight": 28, "quantity": [2, 4]},
        {"item": "high_method", "weight": 8, "quantity": [1, 1]},
        {"item": "high_artifact", "weight": 8, "quantity": [1, 1]},
    ],
}

DROP_ROLLS_BY_EVENT_TYPE = {
    "reward_item": [2, 3],
    "battle": [1, 3],
    "hidden_opportunity": [2, 3],
    "rare_item": [1, 2],
    "hidden_cave": [2, 4],
}
