EXPLORE_EVENTS = [
    {
        "code": "spirit_stone_cache",
        "name": "石缝中的灵光",
        "type": "reward_spirit_stones",
        "weight": 28,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [18, 68]},
        "risks": {},
        "narrative": "你在一处石缝中，察觉到微弱的灵气波动。\n\n拨开碎石，发现几块下品灵石嵌在石壁里，像是有人曾经在这里修炼过，遗落了这些。",
    },
    {
        "code": "wild_spirit_herb",
        "name": "崖边的灵息",
        "type": "reward_item",
        "weight": 26,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"items": [{"code": "healing_herb", "quantity": [1, 3]}]},
        "risks": {},
        "narrative": "峭壁边缘，一株不知名的灵草在风中轻轻摇曳。\n\n它吸收了日月精华，叶片上凝着晨露般的灵液，散发着淡淡的清香。",
    },
    {
        "code": "mana_pill_bottle",
        "name": "古修士的遗物",
        "type": "reward_item",
        "weight": 20,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"items": [{"code": "mana_pill", "quantity": [1, 2]}]},
        "risks": {},
        "narrative": "在一处坍塌的石室中，你发现了一只布满灰尘的丹瓶。\n\n瓶口被灵力封印，打开后，三枚回灵丹静静躺在其中，灵气未散。",
    },
    {
        "code": "low_beast",
        "name": "林深处的低吼",
        "type": "battle",
        "weight": 18,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [20, 80], "items": [{"code": "beast_core", "quantity": [1, 1], "chance": 0.35}]},
        "risks": {"hp_damage": [4, 18]},
        "narrative": "密林深处传来一阵低沉的吼声。\n\n你屏息靠近，只见一只低阶妖兽正在撕食猎物。它察觉到你的存在，猛然抬头，眼中闪过凶光。",
    },
    {
        "code": "injured_cultivator",
        "name": "路边的垂死修士",
        "type": "hidden_opportunity",
        "weight": 8,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [40, 120], "items": [{"code": "broken_jade_slip", "quantity": [1, 1]}]},
        "risks": {},
        "narrative": "山道旁，一个衣衫褴褛的修士倒在血泊中。\n\n他的修为已废，气息奄奄，手中紧握着一枚残破的玉简，似乎想说什么，却只吐出几个字：「莫信……宗门……」",
    },
    {
        "code": "broken_cave",
        "name": "被遗忘的洞府",
        "type": "hidden_opportunity",
        "weight": 6,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [80, 180], "items": [{"code": "black_iron_shard", "quantity": [1, 3]}]},
        "risks": {},
        "narrative": "乱石堆中，你发现了一个被藤蔓遮蔽的洞口。\n\n洞府内陈设简陋，早已人去楼空，只在石案上留下几块黑铁碎片，仿佛在诉说着昔日的故事。",
    },
    {
        "code": "mist_trap",
        "name": "雾中的幻象",
        "type": "trap",
        "weight": 4,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {},
        "risks": {"hp_damage": [5, 16]},
        "narrative": "浓雾忽然漫天袭来，你眼前出现了诡异的幻象：\n\n一个个熟悉的身影在你面前走过，却又在伸手触碰时化为虚无。灵力乱窜，你勉强破阵而出，已是一身冷汗。",
    },
    {
        "code": "empty_trip",
        "name": "无声的山林",
        "type": "empty",
        "weight": 3,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {},
        "risks": {},
        "narrative": "你走了一整天，山林依旧寂静无声。\n\n没有灵草，没有妖兽，甚至连鸟鸣都听不到。你不禁想，是这一带真的贫瘠，还是你的机缘未到？",
    },
]
