EXPLORE_EVENTS = [
    {
        "code": "spirit_stone_cache",
        "name": "捡到灵石",
        "type": "reward_spirit_stones",
        "weight": 34,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [18, 68]},
        "risks": {},
    },
    {
        "code": "wild_spirit_herb",
        "name": "发现灵草",
        "type": "reward_item",
        "weight": 22,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"items": [{"code": "healing_herb", "quantity": [1, 3]}]},
        "risks": {},
    },
    {
        "code": "mana_pill_bottle",
        "name": "拾得丹瓶",
        "type": "reward_item",
        "weight": 14,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"items": [{"code": "mana_pill", "quantity": [1, 2]}]},
        "risks": {},
    },
    {
        "code": "low_beast",
        "name": "遇到低阶妖兽",
        "type": "battle",
        "weight": 22,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [20, 80], "items": [{"code": "beast_core", "quantity": [1, 1], "chance": 0.35}]},
        "risks": {"hp_damage": [4, 18]},
    },
    {
        "code": "injured_cultivator",
        "name": "遇到受伤修士",
        "type": "hidden_opportunity",
        "weight": 6,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [40, 120], "items": [{"code": "broken_jade_slip", "quantity": [1, 1]}]},
        "risks": {},
    },
    {
        "code": "broken_cave",
        "name": "发现残破洞府",
        "type": "hidden_opportunity",
        "weight": 4,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [80, 180], "items": [{"code": "black_iron_shard", "quantity": [1, 3]}]},
        "risks": {},
    },
    {
        "code": "mist_trap",
        "name": "误入迷阵",
        "type": "trap",
        "weight": 8,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {},
        "risks": {"hp_damage": [5, 16]},
    },
    {
        "code": "empty_trip",
        "name": "空手而归",
        "type": "empty",
        "weight": 12,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {},
        "risks": {},
    },
]
