EXPLORE_EVENTS = [
    {
        "code": "spirit_stone_cache",
        "name": "石缝中的灵光",
        "type": "reward_spirit_stones",
        "weight": 28,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [18, 68]},
        "risks": {},
        "narrative": "你在一处不起眼的石缝中搜寻许久，突然察觉到一丝微弱的灵气波动，似有似无。\n\n拨开覆盖在表面的碎石与苔藓，竟发现几块下品灵石嵌在石壁深处，散发着淡淡灵光。\n\n你心中暗想，似乎曾有人在此修炼过，离去时遗落了这些灵石，又或是刻意留下的标记。",
    },
    {
        "code": "wild_spirit_herb",
        "name": "崖边的灵息",
        "type": "reward_item",
        "weight": 26,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"items": [{"code": "healing_herb", "quantity": [1, 3]}]},
        "risks": {},
        "narrative": "峭壁边缘，一株不知名的灵草在山风中轻轻摇曳，仿佛在与天地灵气共鸣。\n\n它不知生长了多少岁月，叶片上凝着晨露般的灵液，晶莹剔透，散发着沁人心脾的清香。\n\n你小心翼翼靠近，心中揣测这灵草已有数十年火候，若能移植回洞府培育，日后必成大用。",
    },
    {
        "code": "mana_pill_bottle",
        "name": "古修士的遗物",
        "type": "reward_item",
        "weight": 20,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"items": [{"code": "mana_pill", "quantity": [1, 2]}]},
        "risks": {},
        "narrative": "在一处坍塌的石室中，你在瓦砾间发现一只布满灰尘的古老丹瓶，瓶身布满岁月痕迹。\n\n瓶口被灵力封印封住，你运转灵力缓缓打开，竟发现三枚回灵丹静静躺在其中，丹香隐隐。\n\n你不禁沉思，这位古修士究竟遭遇了什么，竟将如此珍贵的丹药遗落在此？",
    },
    {
        "code": "low_beast",
        "name": "林深处的低吼",
        "type": "battle",
        "weight": 18,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [20, 80], "items": [{"code": "beast_core", "quantity": [1, 1], "chance": 0.35}]},
        "risks": {"hp_damage": [4, 18]},
        "narrative": "密林深处传来一阵低沉压抑的吼声，在寂静山林中回荡，令人生畏。\n\n你屏住呼吸小心靠近，只见一只低阶妖兽正在撕食猎物，鲜血染红地面。它忽然察觉你的存在，猛然抬头，獠牙外露，眼中闪过凶光。\n\n你心中警惕，这妖兽虽只低阶，但凶性正盛，贸然出手恐有一番恶战。",
    },
    {
        "code": "injured_cultivator",
        "name": "路边的垂死修士",
        "type": "hidden_opportunity",
        "weight": 8,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [40, 120], "items": [{"code": "broken_jade_slip", "quantity": [1, 1]}]},
        "risks": {},
        "narrative": "山道旁，一个衣衫褴褛的修士倒在血泊中，气息微弱，奄奄一息。\n\n他的修为已被人废去，经脉断裂。你上前查看，发现他手中紧握一枚残破玉简，似乎想说什么，却只吐出几个字：「莫信……宗门……」\n\n你心中一震，这话中似有隐情，而玉简中又记载着怎样的真相？",
    },
    {
        "code": "broken_cave",
        "name": "被遗忘的洞府",
        "type": "hidden_opportunity",
        "weight": 6,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {"spirit_stones": [80, 180], "items": [{"code": "black_iron_shard", "quantity": [1, 3]}]},
        "risks": {},
        "narrative": "在一片乱石堆中，你发现了一个被藤蔓遮蔽的洞口，若非刻意搜寻几乎难以发觉。\n\n拨开藤蔓走入洞府，内里陈设简陋，石床石案一应俱全，但早已人去楼空。你在石案上翻找，找到几块黑铁碎片，质地奇特。\n\n你暗自推测，这位前辈不知是飞升而去，还是遭遇不测，留下洞府等待有缘人。",
    },
    {
        "code": "mist_trap",
        "name": "雾中的幻象",
        "type": "trap",
        "weight": 4,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {},
        "risks": {"hp_damage": [5, 16]},
        "narrative": "正当你全神贯注搜寻时，一团浓雾忽然漫天袭来，瞬间将你包围，伸手不见五指。\n\n你眼前出现诡异幻象：一个个熟悉的面容在你面前走过，对你微笑说话，却在触碰瞬间化为虚无。你的灵力在体内乱窜，气血翻涌。\n\n你猛然咬破舌尖，以剧痛唤醒神智，勉强破阵而出，已是一身冷汗。",
    },
    {
        "code": "empty_trip",
        "name": "无声的山林",
        "type": "empty",
        "weight": 3,
        "min_realm": "炼气一层",
        "max_realm": "化神后期",
        "conditions": {},
        "rewards": {},
        "risks": {},
        "narrative": "你在这片山林中搜寻了一整天，从清晨到黄昏，脚步踏遍每一个角落，然而山林依旧寂静无声。\n\n没有灵草的踪影，没有妖兽的气息，甚至连一声鸟鸣都听不到，有的只是风吹树叶的沙沙声。\n\n你不禁揣测，是这一带灵气贫瘠，还是你的机缘未到？又或者，这片山林正隐藏着某种尚未察觉的秘密？",
    },
]
