ITEM_TEMPLATES = [
    {
        "code": "low_spirit_stone",
        "name": "下品灵石",
        "type": "material",
        "grade": 1,
        "description": "蕴含稀薄灵气的低阶灵石，可作为材料或未来交易货币。",
        "stackable": True,
        "max_stack": 999,
        "effects": {},
    },
    {
        "code": "healing_herb",
        "name": "止血草",
        "type": "material",
        "grade": 1,
        "description": "低阶药草，可用于炼制疗伤丹药。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "healing_pill",
        "name": "疗伤丹",
        "type": "pill",
        "grade": 1,
        "description": "服用后恢复气血。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"recover_hp": 80},
    },
    {
        "code": "qi_powder",
        "name": "聚气散",
        "type": "pill",
        "grade": 1,
        "description": "辅助炼气期修士吸纳灵气。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"cultivation": 30},
    },
    {
        "code": "mana_pill",
        "name": "回灵丹",
        "type": "pill",
        "grade": 1,
        "description": "服用后恢复法力。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"recover_mana": 120},
    },
    {
        "code": "foundation_pill",
        "name": "筑基丹",
        "type": "pill",
        "grade": 2,
        "description": "冲击筑基期的关键丹药。",
        "stackable": True,
        "max_stack": 20,
        "effects": {"breakthrough_bonus_once": 0.08},
    },
    {
        "code": "core_pill",
        "name": "结丹丹",
        "type": "pill",
        "grade": 3,
        "description": "冲击结丹期的关键丹药。",
        "stackable": True,
        "max_stack": 20,
        "effects": {"breakthrough_bonus_once": 0.06},
    },
    {
        "code": "nascent_pill",
        "name": "化婴丹",
        "type": "pill",
        "grade": 4,
        "description": "冲击元婴期的珍贵丹药。",
        "stackable": True,
        "max_stack": 10,
        "effects": {"breakthrough_bonus_once": 0.04},
    },
    {
        "code": "black_iron_shard",
        "name": "玄铁碎片",
        "type": "material",
        "grade": 1,
        "description": "炼器材料，可用于日后强化法宝。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "low_material",
        "name": "低阶炼器材",
        "type": "material",
        "grade": 1,
        "description": "常见低阶炼器材料，可用于强化低阶法宝。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "mid_material",
        "name": "中阶炼器材",
        "type": "material",
        "grade": 2,
        "description": "筑基、结丹修士常用炼器材料。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "high_material",
        "name": "高阶炼器材",
        "type": "material",
        "grade": 3,
        "description": "高阶法宝强化材料。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "mid_spirit_stone",
        "name": "中品灵石",
        "type": "material",
        "grade": 2,
        "description": "灵气更充沛的灵石。",
        "stackable": True,
        "max_stack": 999,
        "effects": {},
    },
    {
        "code": "high_spirit_stone",
        "name": "上品灵石",
        "type": "material",
        "grade": 3,
        "description": "高阶修士也会珍惜的灵石。",
        "stackable": True,
        "max_stack": 999,
        "effects": {},
    },
    {
        "code": "low_method",
        "name": "长春功",
        "type": "cultivation_method",
        "grade": 1,
        "description": "平稳温和的炼气期基础功法。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"cultivation_speed": 0.04, "max_mana": 12, "breakthrough_rate": 0.01},
    },
    {
        "code": "mid_method",
        "name": "青元剑诀",
        "type": "cultivation_method",
        "grade": 2,
        "description": "兼具吐纳与斗法的进阶功法。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"cultivation_speed": 0.06, "max_mana": 24, "breakthrough_rate": 0.014},
    },
    {
        "code": "high_method",
        "name": "太虚真诀",
        "type": "cultivation_method",
        "grade": 3,
        "description": "罕见高阶功法，能显著提升修行根基。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"cultivation_speed": 0.08, "max_mana": 40, "breakthrough_rate": 0.018},
    },
    {
        "code": "low_artifact",
        "name": "青锋剑",
        "type": "magic_artifact",
        "grade": 1,
        "description": "低阶攻击法宝，可强化。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"attack": 8, "defense": 5, "explore_reward_bonus": 0.02},
    },
    {
        "code": "mid_artifact",
        "name": "玄铁飞剑",
        "type": "magic_artifact",
        "grade": 2,
        "description": "中阶法宝，攻守兼备。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"attack": 18, "defense": 12, "explore_reward_bonus": 0.035},
    },
    {
        "code": "high_artifact",
        "name": "紫电尺",
        "type": "magic_artifact",
        "grade": 3,
        "description": "高阶法宝，斗法威力惊人。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"attack": 40, "defense": 25, "explore_reward_bonus": 0.05},
    },
    {
        "code": "beast_core",
        "name": "妖兽内丹",
        "type": "material",
        "grade": 2,
        "description": "低阶妖兽凝结的内丹。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "broken_jade_slip",
        "name": "残破玉简",
        "type": "quest_item",
        "grade": 1,
        "description": "记载残缺功法或秘闻的玉简。",
        "stackable": True,
        "max_stack": 20,
        "effects": {},
    },
    {
        "code": "calm_talisman",
        "name": "清心符",
        "type": "quest_item",
        "grade": 1,
        "description": "可压制心神躁动，后续用于心魔玩法。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "basic_storage_bag",
        "name": "低阶储物袋",
        "type": "storage_bag",
        "grade": 1,
        "description": "预留装备实例，未来可打开额外格子。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"storage_slots": 9},
    },
    {
        "code": "spirit_beast_bag",
        "name": "灵兽袋",
        "type": "spirit_beast_bag",
        "grade": 1,
        "description": "预留灵兽系统容器。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"beast_slots": 1},
    },
    {
        "code": "spirit_grass",
        "name": "灵草",
        "type": "material",
        "grade": 1,
        "description": "常见灵草，可用于炼丹。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "clear_dew",
        "name": "清露",
        "type": "material",
        "grade": 1,
        "description": "灵草凝结的露珠，用于炼丹。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "spirit_paper",
        "name": "符纸",
        "type": "material",
        "grade": 1,
        "description": "用于绘制符箓的基础材料。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "spirit_ink",
        "name": "灵墨",
        "type": "material",
        "grade": 1,
        "description": "绘制符箓的墨汁材料。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "formation_flag",
        "name": "阵旗",
        "type": "material",
        "grade": 1,
        "description": "布阵用的小旗，可反复使用。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "spirit_stone_chip",
        "name": "灵石碎屑",
        "type": "material",
        "grade": 1,
        "description": "灵石的碎屑，用于布阵。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "spirit_stone",
        "name": "灵石",
        "type": "material",
        "grade": 1,
        "description": "蕴含灵气的灵石，用于布阵。",
        "stackable": True,
        "max_stack": 999,
        "effects": {},
    },
    {
        "code": "qi_recovery_pill",
        "name": "回气丹",
        "type": "pill",
        "grade": 1,
        "description": "服用后恢复少量法力。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"recover_mana": 8},
    },
    {
        "code": "scout_talisman",
        "name": "探查符",
        "type": "talisman",
        "grade": 1,
        "description": "一次性消耗品，提高秘境触发概率。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"explore_lucky_bonus": 0.05},
    },
    {
        "code": "protect_talisman",
        "name": "护身符",
        "type": "talisman",
        "grade": 1,
        "description": "一次性消耗品，降低探索负面事件概率。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"explore_risk_reduce": 0.08},
    },
    {
        "code": "speed_talisman",
        "name": "速行符",
        "type": "talisman",
        "grade": 1,
        "description": "一次性消耗品，降低探索法力消耗。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"explore_mana_cost_reduce": 3},
    },
    {
        "code": "spirit_gather_artifact",
        "name": "聚灵法器",
        "type": "magic_artifact",
        "grade": 1,
        "description": "提升少量修炼效率的法器。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"cultivation_speed": 0.02},
    },
    {
        "code": "explore_puppet",
        "name": "探索傀儡",
        "type": "puppet",
        "grade": 1,
        "description": "提高少量掉落概率的傀儡。",
        "stackable": True,
        "max_stack": 1,
        "effects": {"explore_reward_bonus": 0.03},
    },
    {
        "code": "spirit_gather_formation",
        "name": "聚灵阵",
        "type": "formation",
        "grade": 1,
        "description": "提升修炼效率的阵法，需要消耗灵石维持。",
        "stackable": True,
        "max_stack": 5,
        "effects": {"cultivation_speed": 0.05, "formation_duration_hours": 1},
    },
    {
        "code": "protect_formation",
        "name": "防护阵",
        "type": "formation",
        "grade": 1,
        "description": "降低探索或突破风险的阵法。",
        "stackable": True,
        "max_stack": 5,
        "effects": {"explore_risk_reduce": 0.1, "formation_duration_hours": 1},
    },
    {
        "code": "attract_formation",
        "name": "引灵阵",
        "type": "formation",
        "grade": 1,
        "description": "增加资源获取概率的阵法。",
        "stackable": True,
        "max_stack": 5,
        "effects": {"explore_reward_bonus": 0.05, "formation_duration_hours": 1},
    },
]
