ITEM_TEMPLATES = [
    {
        "code": "low_spirit_stone",
        "name": "下品灵石",
        "type": "material",
        "grade": 1,
        "description": "蕴含稀薄灵气的低阶灵石，可作为材料或未来交易货币。",
        "stackable": True,
        "max_stack": 999,
        "effects": {},
    },
    {
        "code": "healing_herb",
        "name": "止血草",
        "type": "material",
        "grade": 1,
        "description": "低阶药草，可用于炼制疗伤丹药。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "huichun_pill",
        "name": "回春丹",
        "type": "pill",
        "grade": 1,
        "description": "服用后恢复少量气血。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"recover_hp": 40},
    },
    {
        "code": "yangqi_pill",
        "name": "养气丹",
        "type": "pill",
        "grade": 1,
        "description": "服用后下一次修炼获得小幅加成。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"train_next_bonus": 1},
    },
    {
        "code": "guyu_pill",
        "name": "固元丹",
        "type": "pill",
        "grade": 1,
        "description": "服用后提升下一次突破成功率。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"breakthrough_next_bonus": 1},
    },
    {
        "code": "healing_pill",
        "name": "疗伤丹",
        "type": "pill",
        "grade": 1,
        "description": "服用后恢复气血。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"recover_hp": 80},
    },
    {
        "code": "qi_powder",
        "name": "聚气散",
        "type": "pill",
        "grade": 1,
        "description": "辅助炼气期修士吸纳灵气。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"cultivation": 30},
    },
    {
        "code": "mana_pill",
        "name": "回灵丹",
        "type": "pill",
        "grade": 1,
        "description": "服用后恢复法力。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"recover_mana": 120},
    },
    {
        "code": "foundation_pill",
        "name": "筑基丹",
        "type": "pill",
        "grade": 2,
        "description": "冲击筑基期的关键丹药。",
        "stackable": True,
        "max_stack": 20,
        "effects": {"breakthrough_bonus_once": 0.08},
    },
    {
        "code": "core_pill",
        "name": "结丹丹",
        "type": "pill",
        "grade": 3,
        "description": "冲击结丹期的关键丹药。",
        "stackable": True,
        "max_stack": 20,
        "effects": {"breakthrough_bonus_once": 0.06},
    },
    {
        "code": "nascent_pill",
        "name": "化婴丹",
        "type": "pill",
        "grade": 4,
        "description": "冲击元婴期的珍贵丹药。",
        "stackable": True,
        "max_stack": 10,
        "effects": {"breakthrough_bonus_once": 0.04},
    },
    {
        "code": "black_iron_shard",
        "name": "玄铁碎片",
        "type": "material",
        "grade": 1,
        "description": "炼器材料，可用于日后强化法宝。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "low_material",
        "name": "低阶炼器材",
        "type": "material",
        "grade": 1,
        "description": "常见低阶炼器材料，可用于强化低阶法宝。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "mid_material",
        "name": "中阶炼器材",
        "type": "material",
        "grade": 2,
        "description": "筑基、结丹修士常用炼器材料。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "high_material",
        "name": "高阶炼器材",
        "type": "material",
        "grade": 3,
        "description": "高阶法宝强化材料。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "mid_spirit_stone",
        "name": "中品灵石",
        "type": "material",
        "grade": 2,
        "description": "灵气更充沛的灵石。",
        "stackable": True,
        "max_stack": 999,
        "effects": {},
    },
    {
        "code": "high_spirit_stone",
        "name": "上品灵石",
        "type": "material",
        "grade": 3,
        "description": "高阶修士也会珍惜的灵石。",
        "stackable": True,
        "max_stack": 999,
        "effects": {},
    },
    {
        "code": "low_method",
        "name": "长春功",
        "type": "cultivation_method",
        "grade": 1,
        "description": "平稳温和的炼气期基础功法。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"cultivation_speed": 0.04, "max_mana": 12, "breakthrough_rate": 0.01},
    },
    {
        "code": "mid_method",
        "name": "青元剑诀",
        "type": "cultivation_method",
        "grade": 2,
        "description": "兼具吐纳与斗法的进阶功法。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"cultivation_speed": 0.06, "max_mana": 24, "breakthrough_rate": 0.014},
    },
    {
        "code": "high_method",
        "name": "太虚真诀",
        "type": "cultivation_method",
        "grade": 3,
        "description": "罕见高阶功法，能显著提升修行根基。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"cultivation_speed": 0.08, "max_mana": 40, "breakthrough_rate": 0.018},
    },
    {
        "code": "low_artifact",
        "name": "青锋剑",
        "type": "magic_artifact",
        "grade": 1,
        "description": "低阶攻击法宝，可强化。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"attack": 8, "defense": 5, "explore_reward_bonus": 0.02},
    },
    {
        "code": "mid_artifact",
        "name": "玄铁飞剑",
        "type": "magic_artifact",
        "grade": 2,
        "description": "中阶法宝，攻守兼备。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"attack": 18, "defense": 12, "explore_reward_bonus": 0.035},
    },
    {
        "code": "high_artifact",
        "name": "紫电尺",
        "type": "magic_artifact",
        "grade": 3,
        "description": "高阶法宝，斗法威力惊人。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"attack": 40, "defense": 25, "explore_reward_bonus": 0.05},
    },
    {
        "code": "beast_core",
        "name": "妖兽内丹",
        "type": "material",
        "grade": 2,
        "description": "低阶妖兽凝结的内丹。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "broken_jade_slip",
        "name": "残破玉简",
        "type": "quest_item",
        "grade": 1,
        "description": "记载残缺功法或秘闻的玉简。",
        "stackable": True,
        "max_stack": 20,
        "effects": {},
    },
    {
        "code": "calm_talisman",
        "name": "清心符",
        "type": "quest_item",
        "grade": 1,
        "description": "可压制心神躁动，后续用于心魔玩法。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "basic_storage_bag",
        "name": "低阶储物袋",
        "type": "storage_bag",
        "grade": 1,
        "description": "预留装备实例，未来可打开额外格子。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"storage_slots": 9},
    },
    {
        "code": "spirit_beast_bag",
        "name": "灵兽袋",
        "type": "spirit_beast_bag",
        "grade": 1,
        "description": "预留灵兽系统容器。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"beast_slots": 1},
    },
    {
        "code": "spirit_gather_talisman",
        "name": "聚灵符",
        "type": "talisman",
        "grade": 1,
        "description": "使用后小幅提升修炼效果，持续1次。",
        "stackable": True,
        "max_stack": 20,
        "effects": {"spirit_gather_talisman_charge": 1},
    },
    {
        "code": "avoid_harm_talisman",
        "name": "避祸符",
        "type": "talisman",
        "grade": 1,
        "description": "使用后降低探索中负面事件概率，持续1次。",
        "stackable": True,
        "max_stack": 20,
        "effects": {"avoid_harm_talisman_charge": 1},
    },
    {
        "code": "explore_luck_talisman",
        "name": "探路符",
        "type": "talisman",
        "grade": 1,
        "description": "使用后小幅提升探索机缘和材料获取概率，持续1次。",
        "stackable": True,
        "max_stack": 20,
        "effects": {"explore_luck_talisman_charge": 1},
    },
    {
        "code": "scout_talisman",
        "name": "探路符",
        "type": "talisman",
        "grade": 1,
        "description": "使用后可小幅度提升下一次探索的运气。",
        "stackable": True,
        "max_stack": 20,
        "effects": {"scout_talisman_charge": 1},
    },
    {
        "code": "guard_talisman",
        "name": "护身符",
        "type": "talisman",
        "grade": 1,
        "description": "使用后小幅度降低探索中战斗和陷阱伤害。",
        "stackable": True,
        "max_stack": 20,
        "effects": {"guard_talisman_charge": 1},
    },
    {
        "code": "swift_talisman",
        "name": "疾风符",
        "type": "talisman",
        "grade": 1,
        "description": "使用后小幅度降低下一次探索的法力消耗。",
        "stackable": True,
        "max_stack": 20,
        "effects": {"swift_talisman_charge": 1},
    },
    {
        "code": "hushen_bell",
        "name": "护身铃",
        "type": "magic_artifact",
        "grade": 1,
        "description": "小幅降低探索受伤风险，适合探索型玩家。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"defense": 3, "explore_damage_reduction": 0.04},
    },
    {
        "code": "juqi_jade",
        "name": "聚气玉",
        "type": "magic_artifact",
        "grade": 1,
        "description": "小幅提升修炼收益，适合修炼型玩家。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"cultivation_speed": 0.015},
    },
    {
        "code": "qingmu_pendant",
        "name": "青木佩",
        "type": "magic_artifact",
        "grade": 1,
        "description": "小幅降低探索损耗，适合探索型玩家。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"explore_reward_bonus": 0.015},
    },
    {
        "code": "crafted_low_sword",
        "name": "低阶长剑",
        "type": "magic_artifact",
        "grade": 1,
        "description": "稳定打造的低阶攻击型法宝，属性低于稀有掉落但胜在稳定可靠。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"attack": 6, "defense": 3, "explore_reward_bonus": 0.01},
    },
    {
        "code": "gathering_artifact",
        "name": "聚灵器",
        "type": "magic_artifact",
        "grade": 1,
        "description": "辅助修炼的炼器产物，小幅提升修炼速度。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"attack": 3, "defense": 4, "cultivation_speed": 0.02},
    },
    {
        "code": "explore_puppet",
        "name": "探索傀儡",
        "type": "magic_artifact",
        "grade": 1,
        "description": "辅助探索的炼器产物，小幅提升探索收获。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"attack": 2, "defense": 3, "explore_reward_bonus": 0.015},
    },
    {
        "code": "foundation_pill_formula",
        "name": "Foundation Pill Formula",
        "type": "recipe_scroll",
        "grade": 2,
        "description": "Unlocks the basic foundation pill recipe.",
        "stackable": True,
        "max_stack": 5,
        "effects": {},
    },
    {
        "code": "swift_talisman_formula",
        "name": "Swift Talisman Formula",
        "type": "recipe_scroll",
        "grade": 1,
        "description": "Unlocks the swift talisman recipe.",
        "stackable": True,
        "max_stack": 5,
        "effects": {},
    },
    {
        "code": "explore_puppet_formula",
        "name": "Explore Puppet Formula",
        "type": "recipe_scroll",
        "grade": 1,
        "description": "Unlocks the exploration puppet recipe.",
        "stackable": True,
        "max_stack": 5,
        "effects": {},
    },
]
