ITEM_TEMPLATES = [
    {
        "code": "healing_herb",
        "name": "止血草",
        "type": "material",
        "grade": 1,
        "description": "低阶药草，可用于炼制疗伤丹药。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "qi_powder",
        "name": "聚气散",
        "type": "pill",
        "grade": 1,
        "description": "辅助炼气期修士吸纳灵气。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"cultivation": 30},
    },
    {
        "code": "mana_pill",
        "name": "回灵丹",
        "type": "pill",
        "grade": 1,
        "description": "服用后恢复法力。",
        "stackable": True,
        "max_stack": 99,
        "effects": {"recover_mana": 120},
    },
    {
        "code": "black_iron_shard",
        "name": "玄铁碎片",
        "type": "material",
        "grade": 1,
        "description": "炼器材料，可用于日后强化法宝。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "beast_core",
        "name": "妖兽内丹",
        "type": "material",
        "grade": 2,
        "description": "低阶妖兽凝结的内丹。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "broken_jade_slip",
        "name": "残破玉简",
        "type": "quest_item",
        "grade": 1,
        "description": "记载残缺功法或秘闻的玉简。",
        "stackable": True,
        "max_stack": 20,
        "effects": {},
    },
    {
        "code": "calm_talisman",
        "name": "清心符",
        "type": "quest_item",
        "grade": 1,
        "description": "可压制心神躁动，后续用于心魔玩法。",
        "stackable": True,
        "max_stack": 99,
        "effects": {},
    },
    {
        "code": "basic_storage_bag",
        "name": "低阶储物袋",
        "type": "storage_bag",
        "grade": 1,
        "description": "预留装备实例，未来可打开额外格子。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"storage_slots": 9},
    },
    {
        "code": "spirit_beast_bag",
        "name": "灵兽袋",
        "type": "spirit_beast_bag",
        "grade": 1,
        "description": "预留灵兽系统容器。",
        "stackable": False,
        "max_stack": 1,
        "effects": {"beast_slots": 1},
    },
]
