from backend.configs.realms import REALM_NAMES


CRAFTING_RECIPES = [
    {
        "id": "craft_qingmu_pendant",
        "name": "青木佩",
        "skill_type": "crafting",
        "required_items": [
            {"code": "low_material", "quantity": 4},
            {"code": "low_spirit_stone", "quantity": 10},
        ],
        "mana_cost": 24,
        "output_item_id": "qingmu_pendant",
        "output_count": 1,
        "required_realm": REALM_NAMES[1],
        "success_rate": 1.0,
    },
    {
        "id": "craft_juqi_jade",
        "name": "聚气玉",
        "skill_type": "crafting",
        "required_items": [
            {"code": "low_material", "quantity": 4},
            {"code": "low_spirit_stone", "quantity": 12},
        ],
        "mana_cost": 26,
        "output_item_id": "juqi_jade",
        "output_count": 1,
        "required_realm": REALM_NAMES[2],
        "success_rate": 1.0,
    },
    {
        "id": "craft_hushen_bell",
        "name": "护身铃",
        "skill_type": "crafting",
        "required_items": [
            {"code": "low_material", "quantity": 5},
            {"code": "low_spirit_stone", "quantity": 14},
        ],
        "mana_cost": 28,
        "output_item_id": "hushen_bell",
        "output_count": 1,
        "required_realm": REALM_NAMES[3],
        "success_rate": 1.0,
    },
    {
        "id": "craft_low_sword",
        "name": "低阶长剑",
        "skill_type": "crafting",
        "required_items": [
            {"code": "low_material", "quantity": 6},
            {"code": "low_spirit_stone", "quantity": 16},
        ],
        "mana_cost": 28,
        "output_item_id": "crafted_low_sword",
        "output_count": 1,
        "required_realm": REALM_NAMES[0],
        "success_rate": 1.0,
    },
    {
        "id": "craft_gathering_artifact",
        "name": "聚灵器",
        "skill_type": "crafting",
        "required_items": [
            {"code": "low_material", "quantity": 6},
            {"code": "low_spirit_stone", "quantity": 12},
        ],
        "mana_cost": 30,
        "output_item_id": "gathering_artifact",
        "output_count": 1,
        "required_realm": REALM_NAMES[2],
        "success_rate": 1.0,
    },
    {
        "id": "craft_explore_puppet",
        "name": "探索傀儡",
        "skill_type": "crafting",
        "required_items": [
            {"code": "low_material", "quantity": 8},
            {"code": "beast_core", "quantity": 1},
        ],
        "mana_cost": 38,
        "output_item_id": "explore_puppet",
        "output_count": 1,
        "required_realm": REALM_NAMES[5],
        "success_rate": 1.0,
        "unlock_item": "explore_puppet_formula",
    },
]
