from backend.configs.realms import REALM_NAMES


TALISMAN_RECIPES = [
    {
        "id": "talisman_explore_luck",
        "name": "探路符",
        "skill_type": "talisman",
        "required_items": [
            {"code": "low_material", "quantity": 1},
            {"code": "low_spirit_stone", "quantity": 3},
        ],
        "mana_cost": 14,
        "output_item_id": "explore_luck_talisman",
        "output_count": 1,
        "required_realm": REALM_NAMES[0],
        "success_rate": 1.0,
    },
    {
        "id": "talisman_avoid_harm",
        "name": "避祸符",
        "skill_type": "talisman",
        "required_items": [
            {"code": "calm_talisman", "quantity": 1},
            {"code": "low_material", "quantity": 1},
        ],
        "mana_cost": 14,
        "output_item_id": "avoid_harm_talisman",
        "output_count": 1,
        "required_realm": REALM_NAMES[0],
        "success_rate": 1.0,
    },
    {
        "id": "talisman_spirit_gather",
        "name": "聚灵符",
        "skill_type": "talisman",
        "required_items": [
            {"code": "low_material", "quantity": 2},
            {"code": "low_spirit_stone", "quantity": 5},
        ],
        "mana_cost": 18,
        "output_item_id": "spirit_gather_talisman",
        "output_count": 1,
        "required_realm": REALM_NAMES[2],
        "success_rate": 1.0,
    },
    {
        "id": "talisman_scout",
        "name": "探路符",
        "skill_type": "talisman",
        "required_items": [
            {"code": "low_material", "quantity": 1},
            {"code": "low_spirit_stone", "quantity": 4},
        ],
        "mana_cost": 16,
        "output_item_id": "scout_talisman",
        "output_count": 1,
        "required_realm": REALM_NAMES[0],
        "success_rate": 1.0,
    },
    {
        "id": "talisman_guard",
        "name": "护身符",
        "skill_type": "talisman",
        "required_items": [
            {"code": "calm_talisman", "quantity": 1},
            {"code": "low_material", "quantity": 1},
        ],
        "mana_cost": 16,
        "output_item_id": "guard_talisman",
        "output_count": 1,
        "required_realm": REALM_NAMES[0],
        "success_rate": 1.0,
    },
    {
        "id": "talisman_swift",
        "name": "疾风符",
        "skill_type": "talisman",
        "required_items": [
            {"code": "low_material", "quantity": 2},
            {"code": "low_spirit_stone", "quantity": 6},
        ],
        "mana_cost": 22,
        "output_item_id": "swift_talisman",
        "output_count": 1,
        "required_realm": REALM_NAMES[3],
        "success_rate": 1.0,
        "unlock_item": "swift_talisman_formula",
    },
]
