FACTIONS = {
    "righteous": {"name": "正道", "enemies": ["demonic", "ghost"], "subtle": ["buddhist"]},
    "demonic": {"name": "魔道", "enemies": ["righteous", "buddhist"], "subtle": ["ghost"]},
    "ghost": {"name": "鬼道", "enemies": ["righteous", "buddhist"], "subtle": ["demonic"]},
    "buddhist": {"name": "佛道", "enemies": ["demonic", "ghost"], "subtle": ["righteous"]},
}

NPC_SECTS = [
    {
        "code": "qingxuan_sword_sect",
        "name": "青玄剑宗",
        "faction": "righteous",
        "level": 3,
        "description": "正道剑修宗门，重视剑诀与斗法。",
        "required_realm": "炼气三层",
        "required_spirit_stones": 0,
        "preferred_root": ["金", "风", "雷"],
        "specialty": ["剑诀", "法宝", "斗法"],
    },
    {
        "code": "taiqing_alchemy_pavilion",
        "name": "太清丹阁",
        "faction": "righteous",
        "level": 3,
        "description": "正道丹修宗门，善炼灵丹，也收纳稳重修士。",
        "required_realm": "炼气二层",
        "required_spirit_stones": 20,
        "preferred_root": ["木", "火", "水"],
        "specialty": ["丹药", "材料", "回灵"],
    },
    {
        "code": "xuesha_gate",
        "name": "血煞门",
        "faction": "demonic",
        "level": 3,
        "description": "魔道斗法宗门，行事狠辣，奖惩分明。",
        "required_realm": "炼气三层",
        "required_spirit_stones": 0,
        "preferred_root": ["火", "暗", "雷"],
        "specialty": ["魔功", "攻击法宝", "心魔"],
    },
    {
        "code": "yinluo_cult",
        "name": "阴罗教",
        "faction": "demonic",
        "level": 3,
        "description": "魔道秘教，擅使阴煞秘术和诡谲法器。",
        "required_realm": "炼气二层",
        "required_spirit_stones": 20,
        "preferred_root": ["暗", "水", "土"],
        "specialty": ["秘术", "材料", "法器"],
    },
    {
        "code": "youming_valley",
        "name": "幽冥谷",
        "faction": "ghost",
        "level": 3,
        "description": "鬼道宗门，擅控魂役鬼，常出没阴脉之地。",
        "required_realm": "炼气三层",
        "required_spirit_stones": 0,
        "preferred_root": ["暗", "水", "冰"],
        "specialty": ["鬼道功法", "控魂法宝", "阴魂材料"],
    },
    {
        "code": "whitebone_temple",
        "name": "白骨观",
        "faction": "ghost",
        "level": 2,
        "description": "鬼道旁门，门规森冷，重视材料与秘法传承。",
        "required_realm": "炼气二层",
        "required_spirit_stones": 10,
        "preferred_root": ["土", "暗", "金"],
        "specialty": ["阴骨材料", "防御法器", "秘法"],
    },
    {
        "code": "golden_lotus_temple",
        "name": "金莲寺",
        "faction": "buddhist",
        "level": 3,
        "description": "佛道禅修宗门，护持心神，擅降魔法器。",
        "required_realm": "炼气二层",
        "required_spirit_stones": 0,
        "preferred_root": ["光", "土", "金"],
        "specialty": ["降魔法器", "清心丹药", "防御功法"],
    },
    {
        "code": "dajue_monastery",
        "name": "大觉禅院",
        "faction": "buddhist",
        "level": 3,
        "description": "佛道大派，讲究根基与心性，适合稳健修行。",
        "required_realm": "炼气三层",
        "required_spirit_stones": 10,
        "preferred_root": ["光", "木", "水"],
        "specialty": ["禅修", "疗伤", "心魔压制"],
    },
]

POSITION_ORDER = ["outer_disciple", "inner_disciple", "elite_disciple", "deacon", "elder", "grand_elder", "leader"]

POSITION_NAMES = {
    "righteous": {
        "outer_disciple": "外门弟子",
        "inner_disciple": "内门弟子",
        "elite_disciple": "精英弟子",
        "deacon": "执事",
        "elder": "长老",
        "grand_elder": "大长老",
        "leader": "掌门",
    },
    "demonic": {
        "outer_disciple": "外门门徒",
        "inner_disciple": "内门门徒",
        "elite_disciple": "血衣弟子",
        "deacon": "护法",
        "elder": "长老",
        "grand_elder": "副门主",
        "leader": "门主",
    },
    "ghost": {
        "outer_disciple": "入门弟子",
        "inner_disciple": "役鬼弟子",
        "elite_disciple": "阴使",
        "deacon": "护法",
        "elder": "长老",
        "grand_elder": "大长老",
        "leader": "谷主",
    },
    "buddhist": {
        "outer_disciple": "沙弥",
        "inner_disciple": "武僧",
        "elite_disciple": "禅师",
        "deacon": "首座",
        "elder": "长老",
        "grand_elder": "监院",
        "leader": "方丈",
    },
}

PROMOTION_RULES = {
    "inner_disciple": {"from": "outer_disciple", "contribution": 100, "realm": "炼气五层"},
    "elite_disciple": {"from": "inner_disciple", "contribution": 260, "realm": "炼气八层"},
    "deacon": {"from": "elite_disciple", "contribution": 560, "realm": "筑基初期"},
    "elder": {"from": "deacon", "contribution": 1200, "realm": "结丹初期"},
    "grand_elder": {"from": "elder", "contribution": 2600, "realm": "元婴初期"},
}

SECT_TASKS = [
    {
        "code": "patrol_mountain",
        "name": "巡守山门",
        "type": "patrol",
        "faction": ["righteous", "buddhist"],
        "required_position": "outer_disciple",
        "target": 1,
        "cost": {"mana": 20},
        "reward": {"contribution": 20, "spirit_stones": 30},
        "reputation": 8,
        "description": "巡守山门，防备邪修窥探。",
    },
    {
        "code": "gather_low_material",
        "name": "采集炼器材",
        "type": "gather_material",
        "faction": ["righteous", "demonic", "ghost", "buddhist"],
        "required_position": "outer_disciple",
        "target": 2,
        "required_items": [{"code": "low_material", "quantity": 2}],
        "reward": {"contribution": 35, "spirit_stones": 45, "items": [{"code": "mana_pill", "quantity": 1}]},
        "reputation": 6,
        "description": "交付低阶炼器材，为宗门库房补充物资。",
    },
    {
        "code": "hunt_low_beast",
        "name": "猎杀妖兽",
        "type": "hunt_beast",
        "faction": ["righteous", "demonic", "ghost"],
        "required_position": "outer_disciple",
        "target": 1,
        "cost": {"mana": 25},
        "reward": {"contribution": 45, "spirit_stones": 55, "items": [{"code": "healing_pill", "quantity": 1}]},
        "reputation": 8,
        "description": "清理宗门周边妖兽，顺便磨炼斗法。",
    },
    {
        "code": "donate_stones",
        "name": "捐献灵石",
        "type": "donate_spirit_stones",
        "faction": ["righteous", "demonic", "ghost", "buddhist"],
        "required_position": "outer_disciple",
        "target": 1,
        "required_spirit_stones": 80,
        "reward": {"contribution": 70},
        "reputation": 5,
        "description": "向宗门库房捐献灵石，快速积累贡献。",
    },
    {
        "code": "method_insight",
        "name": "参悟功法",
        "type": "train_method",
        "faction": ["righteous", "demonic", "ghost", "buddhist"],
        "required_position": "inner_disciple",
        "target": 1,
        "cost": {"mana": 15},
        "reward": {"contribution": 55, "spirit_stones": 35},
        "reputation": 7,
        "description": "在宗门藏经处参悟主修功法心得。",
    },
    {
        "code": "secret_probe",
        "name": "探查秘境",
        "type": "explore_secret",
        "faction": ["righteous", "demonic", "ghost", "buddhist"],
        "required_position": "elite_disciple",
        "target": 1,
        "cost": {"mana": 35},
        "reward": {"contribution": 95, "spirit_stones": 100, "items": [{"code": "foundation_pill", "quantity": 1}]},
        "reputation": 12,
        "description": "前往宗门标记的秘境外围探查。",
    },
    {
        "code": "faction_conflict",
        "name": "阵营冲突",
        "type": "faction_conflict",
        "faction": ["righteous", "demonic", "ghost", "buddhist"],
        "required_position": "inner_disciple",
        "target": 1,
        "cost": {"mana": 40},
        "reward": {"contribution": 120, "spirit_stones": 120, "items": [{"code": "low_artifact", "quantity": 1}]},
        "reputation": 18,
        "description": "参与一次小规模阵营冲突，本版以后端模拟完成。",
    },
]

SECT_SHOP = {
    "righteous": [
        {"code": "sect_mana_pill", "name": "宗门回灵丹", "cost": 40, "item_code": "mana_pill", "quantity": 2},
        {"code": "sect_method", "name": "宗门基础功法", "cost": 120, "item_code": "low_method", "quantity": 1},
        {"code": "sect_artifact", "name": "制式飞剑", "cost": 160, "item_code": "low_artifact", "quantity": 1},
        {"code": "sect_foundation_pill", "name": "筑基丹", "cost": 260, "item_code": "foundation_pill", "quantity": 1},
    ],
    "demonic": [
        {"code": "blood_mana_pill", "name": "血炼回灵丹", "cost": 35, "item_code": "mana_pill", "quantity": 2, "inner_demon": 2},
        {"code": "demonic_method", "name": "魔道基础功法", "cost": 120, "item_code": "low_method", "quantity": 1},
        {"code": "demonic_artifact", "name": "血纹法器", "cost": 150, "item_code": "low_artifact", "quantity": 1},
    ],
    "ghost": [
        {"code": "ghost_material", "name": "阴魂材料", "cost": 50, "item_code": "low_material", "quantity": 4},
        {"code": "ghost_method", "name": "鬼道基础功法", "cost": 120, "item_code": "low_method", "quantity": 1},
        {"code": "ghost_artifact", "name": "控魂法器", "cost": 150, "item_code": "low_artifact", "quantity": 1},
    ],
    "buddhist": [
        {"code": "lotus_pill", "name": "金莲疗伤丹", "cost": 40, "item_code": "healing_pill", "quantity": 2, "inner_demon": -2},
        {"code": "buddhist_method", "name": "禅修基础功法", "cost": 120, "item_code": "low_method", "quantity": 1},
        {"code": "buddhist_artifact", "name": "降魔法器", "cost": 160, "item_code": "low_artifact", "quantity": 1},
    ],
}
