TASKS = [
    {
        "id": "task_001",
        "name": "初识吐纳",
        "type": "train",
        "target": 3,
        "reward": {"spirit_stones": 120, "items": [{"code": "mana_pill", "quantity": 1}]},
        "description": "导引灵气入体，是修行的第一步。完成三次吐纳，让身体记住灵气流转的感觉。",
        "narrative_hint": "你盘膝而坐，按照功法口诀，第一次感受到了灵气……",
    },
    {
        "id": "task_002",
        "name": "山野初涉",
        "type": "explore",
        "target": 3,
        "reward": {"spirit_stones": 180, "items": [{"code": "qi_powder", "quantity": 2}]},
        "description": "只在洞府中修行是不够的。踏入山野，感受天地灵气在自然中的流动，你会学到书本上没有的东西。",
        "narrative_hint": "你第一次走出洞府，山风迎面，带着灵草和泥土的气味……",
    },
    {
        "id": "task_003",
        "name": "功法初涉",
        "type": "learn_method",
        "target": 1,
        "reward": {"spirit_stones": 220, "items": [{"code": "mana_pill", "quantity": 2}]},
        "description": "一本功法，就是一条修行之路。选择适合你灵根的功法，认真学习，为筑基打好根基。",
        "narrative_hint": "你翻开功法第一页，上面的口诀……好像隐约在哪里听到过？",
    },
    {
        "id": "task_004",
        "name": "法宝初携",
        "type": "equip_artifact",
        "target": 1,
        "reward": {"spirit_stones": 220, "items": [{"code": "low_material", "quantity": 4}]},
        "description": "修仙路上，不是所有危险都能靠肉身硬抗。一件法宝，也许就是你与死亡之间的那道防线。",
        "narrative_hint": "你将法宝握在手中，感受到其中灵气的脉动……这感觉，让人安心。",
    },
    {
        "id": "task_005",
        "name": "筑基问道",
        "type": "breakthrough_realm",
        "target": 1,
        "target_realm_stage": "筑基",
        "reward": {"spirit_stones": 300, "items": [{"code": "mid_material", "quantity": 2}]},
        "description": "筑基——这是修仙之路真正开始的地方。从'感应灵气的人'变成'真正修仙的人'，只差这一步。",
        "narrative_hint": "你感受到丹田中的灵气开始凝聚……这一次，如果能成，你的人生将彻底不同。",
    },
]

TASK_BY_ID = {task["id"]: task for task in TASKS}
